apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: setup-grafana-datasource
  name: setup-grafana-datasource
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: setup-grafana-datasource
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: setup-grafana-datasource
    spec:
      containers:
        - args:
            - /create.sh
          image: appropriate/curl
          name: setup-grafana-datasource
          resources: {}
          volumeMounts:
            - mountPath: /create.sh
              name: setup-grafana-datasource-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: setup-grafana-datasource-claim0
          persistentVolumeClaim:
            claimName: setup-grafana-datasource-claim0
            readOnly: true
status: {}
